import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/annotations">Annotations</Link>
        </li>
        <li>
          <Link to="/affiliateurl">AffiliateURL</Link>
        </li>
        <li>
          <Link to="/itemavailability">ItemAvailability</Link>
        </li>
        <li>
          <Link to="/automatedemailsending">AutomatedEmailSending</Link>
        </li>
        <li>
          <Link to="/scheduling">Scheduling</Link>
        </li>
        <li>
          <Link to="/facetagging">FaceTagging</Link>
        </li>
        <li>
          <Link to="/baslinereporting">BaslineReporting</Link>
        </li>
        <li>
          <Link to="/accountscore">AccountScore</Link>
        </li>
        <li>
          <Link to="/adhocreporting">AdhocReporting</Link>
        </li>
        <li>
          <Link to="/certificationtracking">CertificationTracking</Link>
        </li>
        <li>
          <Link to="/customisedorderstatus">CustomisedOrderStatus</Link>
        </li>
        <li>
          <Link to="/feedback">Feedback</Link>
        </li>
        <li>
          <Link to="/cenralizedbilling">CenralizedBilling</Link>
        </li>
        <li>
          <Link to="/appupdates">AppUpdates</Link>
        </li>
        <li>
          <Link to="/audiomusic">AudioMusic</Link>
        </li>
        <li>
          <Link to="/appointmentmanagement">AppointmentManagement</Link>
        </li>
        <li>
          <Link to="/auctionbidding">AuctionBIdding</Link>
        </li>
        <li>
          <Link to="/leaderboard">Leaderboard</Link>
        </li>
        <li>
          <Link to="/itemgrouper">ItemGrouper</Link>
        </li>
        <li>
          <Link to="/dailyschedulenotification">DailyScheduleNotification</Link>
        </li>
        <li>
          <Link to="/tasklist">Tasklist</Link>
        </li>
        <li>
          <Link to="/multiplegesturerecogniser">MultipleGestureRecogniser</Link>
        </li>
        <li>
          <Link to="/categoriessubcategories">CategoriesSubCategories</Link>
        </li>
        <li>
          <Link to="/accounttransfer">AccountTransfer</Link>
        </li>
        <li>
          <Link to="/admanager">AdManager</Link>
        </li>
        <li>
          <Link to="/cvresumecandidatemanagement">
            CVResumeCandidateManagement
          </Link>
        </li>
        <li>
          <Link to="/ordertracking">OrderTracking</Link>
        </li>
        <li>
          <Link to="/feedbackcollection">FeedbackCollection</Link>
        </li>
        <li>
          <Link to="/collecttransactionfees">CollectTransactionFees</Link>
        </li>
        <li>
          <Link to="/blockusers">BlockUsers</Link>
        </li>
        <li>
          <Link to="/audiocall">AudioCall</Link>
        </li>
        <li>
          <Link to="/convertfiles">ConvertFiles</Link>
        </li>
        <li>
          <Link to="/couponcodegenerator">CouponCodeGenerator</Link>
        </li>
        <li>
          <Link to="/multiplayersupport">MultiplayerSupport</Link>
        </li>
        <li>
          <Link to="/mapsettings">MapSettings</Link>
        </li>
        <li>
          <Link to="/desktopnotification">DesktopNotification</Link>
        </li>
        <li>
          <Link to="/teambuilder">TeamBuilder</Link>
        </li>
        <li>
          <Link to="/productrecommendationengine">
            ProductRecommendationEngine
          </Link>
        </li>
        <li>
          <Link to="/creditdebitcardpayments">CreditDebitCardPayments</Link>
        </li>
        <li>
          <Link to="/activitylog">ActivityLog</Link>
        </li>
        <li>
          <Link to="/budgetingforecasting">BudgetingForecasting</Link>
        </li>
        <li>
          <Link to="/demoaccount">DemoAccount</Link>
        </li>
        <li>
          <Link to="/expensetracking">ExpenseTracking</Link>
        </li>
        <li>
          <Link to="/googlelogin">GoogleLogin</Link>
        </li>
        <li>
          <Link to="/donationpayments">DonationPayments</Link>
        </li>
        <li>
          <Link to="/cameraaccess">CameraAccess</Link>
        </li>
        <li>
          <Link to="/downloadoptions">DownloadOptions</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/scoring">Scoring</Link>
        </li>
        <li>
          <Link to="/map">Map</Link>
        </li>
        <li>
          <Link to="/emailnotification">EmailNotification</Link>
        </li>
        <li>
          <Link to="/automatedprioritisation">AutomatedPrioritisation</Link>
        </li>
        <li>
          <Link to="/repeaingtasks">RepeaingTasks</Link>
        </li>
        <li>
          <Link to="/ganttchart">GanttChart</Link>
        </li>
        <li>
          <Link to="/customisableusersubscri">Customisableusersubscri</Link>
        </li>
        <li>
          <Link to="/dailyemailsignup">DailyEmailSignUp</Link>
        </li>
        <li>
          <Link to="/fromapprovalworkflow">FromApprovalWorkflow</Link>
        </li>
        <li>
          <Link to="/expressdelivery">ExpressDelivery</Link>
        </li>
        <li>
          <Link to="/polling">Polling</Link>
        </li>
        <li>
          <Link to="/invoicebilling">InvoiceBilling</Link>
        </li>
        <li>
          <Link to="/captcha">Captcha</Link>
        </li>
        <li>
          <Link to="/audiolibrary">AudioLibrary</Link>
        </li>
        <li>
          <Link to="/googlecalendersync">GoogleCalenderSync</Link>
        </li>
        <li>
          <Link to="/discountsoffers">DiscountsOffers</Link>
        </li>
        <li>
          <Link to="/gamescore">GameScore</Link>
        </li>
        <li>
          <Link to="/ordersummary">Ordersummary</Link>
        </li>
        <li>
          <Link to="/enablelinkedaccounts">EnableLinkedAccounts</Link>
        </li>
        <li>
          <Link to="/smartcategorisation">SmartCategorisation</Link>
        </li>
        <li>
          <Link to="/ideamanagement">IdeaManagement</Link>
        </li>
        <li>
          <Link to="/dailytimelimit">DailyTimeLimit</Link>
        </li>
        <li>
          <Link to="/leadmanagement">LeadManagement</Link>
        </li>
        <li>
          <Link to="/orderdetailview">Orderdetailview</Link>
        </li>
        <li>
          <Link to="/questionbank">QuestionBank</Link>
        </li>
        <li>
          <Link to="/multiplecurrencysupport">Multiplecurrencysupport</Link>
        </li>
        <li>
          <Link to="/contentdeliverynetwork">ContentDeliveryNetwork</Link>
        </li>
        <li>
          <Link to="/audioslideshow">AudioSlideShow</Link>
        </li>
        <li>
          <Link to="/icalendersupport">ICalenderSupport</Link>
        </li>
        <li>
          <Link to="/favourites">Favourites</Link>
        </li>
        <li>
          <Link to="/pricingengine">PricingEngine</Link>
        </li>
        <li>
          <Link to="/locationbasedalerts">LocationBasedAlerts</Link>
        </li>
        <li>
          <Link to="/leavetracker">LeaveTracker</Link>
        </li>
        <li>
          <Link to="/stereoscopicdisplay">StereoscopicDisplay</Link>
        </li>
        <li>
          <Link to="/notificationsettings">NotificationSettings</Link>
        </li>
        <li>
          <Link to="/dashboardguests">DashboardGuests</Link>
        </li>
        <li>
          <Link to="/emaillist">EmailList</Link>
        </li>
        <li>
          <Link to="/organisationhierarchy">OrganisationHierarchy</Link>
        </li>
        <li>
          <Link to="/waitinglist">WaitingList</Link>
        </li>
        <li>
          <Link to="/paymentadmin">PaymentAdmin</Link>
        </li>
        <li>
          <Link to="/countrycodeblocking">CountryCodeBlocking</Link>
        </li>
        <li>
          <Link to="/callrecording">CallRecording</Link>
        </li>
        <li>
          <Link to="/kanbanboard">KanbanBoard</Link>
        </li>
        <li>
          <Link to="/freecredits">FreeCredits</Link>
        </li>
        <li>
          <Link to="/qrcode">QRCode</Link>
        </li>
        <li>
          <Link to="/notifications">Notifications</Link>
        </li>
        <li>
          <Link to="/prioritise">Prioritise</Link>
        </li>
        <li>
          <Link to="/targettedfeed">TargettedFeed</Link>
        </li>
        <li>
          <Link to="/projectportfolioone">ProjectPortfolioOne</Link>
        </li>
        <li>
          <Link to="/livechatsummary">LiveChatSummary</Link>
        </li>
        <li>
          <Link to="/events">Events</Link>
        </li>
        <li>
          <Link to="/switchaccount">SwitchAccount</Link>
        </li>
        <li>
          <Link to="/review">Review</Link>
        </li>
        <li>
          <Link to="/payments">Payments</Link>
        </li>
        <li>
          <Link to="/customisableuserprofile">CustomisableUserProfile</Link>
        </li>
        <li>
          <Link to="/playlist">Playlist</Link>
        </li>
        <li>
          <Link to="/datastorage">DataStorage</Link>
        </li>
        <li>
          <Link to="/guestlogin">GuestLogin</Link>
        </li>
        <li>
          <Link to="/requestmanagement">RequestManagement</Link>
        </li>
        <li>
          <Link to="/pushnotifications">PushNotifications</Link>
        </li>
        <li>
          <Link to="/reviewapproval">ReviewApproval</Link>
        </li>
        <li>
          <Link to="/textcomparison">TextComparison</Link>
        </li>
        <li>
          <Link to="/projectreporting">ProjectReporting</Link>
        </li>
        <li>
          <Link to="/projectstracking">ProjectsTracking</Link>
        </li>
        <li>
          <Link to="/graphicalcharts">GraphicalCharts</Link>
        </li>
        <li>
          <Link to="/timetrackingbilling">TimeTrackingBilling</Link>
        </li>
        <li>
          <Link to="/premiumplancomparison">PremiumPlanComparison</Link>
        </li>
        <li>
          <Link to="/dataencryption">Dataencryption</Link>
        </li>
        <li>
          <Link to="/languageoptions">Languageoptions</Link>
        </li>
        <li>
          <Link to="/loyaltysystem">LoyaltySystem</Link>
        </li>
        <li>
          <Link to="/rfid">RFID</Link>
        </li>
        <li>
          <Link to="/taskallocator">TaskAllocator</Link>
        </li>
        <li>
          <Link to="/visualsearch">VisualSearch</Link>
        </li>
        <li>
          <Link to="/projectportfolio">ProjectPortfolio</Link>
        </li>
        <li>
          <Link to="/remoteadministration">RemoteAdministration</Link>
        </li>
        <li>
          <Link to="/inventorytrendanalysis">InventoryTrendAnalysis</Link>
        </li>
        <li>
          <Link to="/timesheetmanagement">TimesheetManagement</Link>
        </li>
        <li>
          <Link to="/ticketsystem">TicketSystem</Link>
        </li>
        <li>
          <Link to="/refundmanagement">RefundManagement</Link>
        </li>
        <li>
          <Link to="/disableads">Disableads</Link>
        </li>
        <li>
          <Link to="/languagesupport">LanguageSupport</Link>
        </li>
        <li>
          <Link to="/print">Print</Link>
        </li>
        <li>
          <Link to="/summarycard">Summarycard</Link>
        </li>
        <li>
          <Link to="/taskblocker">TaskBlocker</Link>
        </li>
        <li>
          <Link to="/qatracker">QATracker</Link>
        </li>
        <li>
          <Link to="/rolespermissions">RolesPermissions</Link>
        </li>
        <li>
          <Link to="/pledgetracking">PledgeTracking</Link>
        </li>
        <li>
          <Link to="/usergroups">UserGroups</Link>
        </li>
        <li>
          <Link to="/usageinsights">UsageInsights</Link>
        </li>
        <li>
          <Link to="/reorderpurchase">ReorderPurchase</Link>
        </li>
        <li>
          <Link to="/downloadpermission">DownloadPermission</Link>
        </li>
        <li>
          <Link to="/productquickview">ProductQuickview</Link>
        </li>
        <li>
          <Link to="/taskviews">TaskViews</Link>
        </li>
        <li>
          <Link to="/quotemanagement">QuoteManagement</Link>
        </li>
        <li>
          <Link to="/referrals">Referrals</Link>
        </li>
        <li>
          <Link to="/savedcards">SavedCards</Link>
        </li>
        <li>
          <Link to="/invitefriends">InviteFriends</Link>
        </li>
        <li>
          <Link to="/shippingaddressvalidation">ShippingAddressValidation</Link>
        </li>
        <li>
          <Link to="/taskallocatorone">TaskAllocatorOne</Link>
        </li>
        <li>
          <Link to="/salesreporting">SalesReporting</Link>
        </li>
        <li>
          <Link to="/taxcalculator">TaxCalculator</Link>
        </li>
        <li>
          <Link to="/emaildeliverability">EmailDeliverability</Link>
        </li>
        <li>
          <Link to="/onboardingguide">OnboardingGuide</Link>
        </li>
        <li>
          <Link to="/shippingchargecalculator">ShippingChargeCalculator</Link>
        </li>
        <li>
          <Link to="/searchtermsreport">SearchTermsReport</Link>
        </li>
        <li>
          <Link to="/geofence">Geofence</Link>
        </li>
        <li>
          <Link to="/performancetracker">PerformanceTracker</Link>
        </li>
        <li>
          <Link to="/shoppingcart">ShoppingCart</Link>
        </li>
        <li>
          <Link to="/statisticsreports">StatisticsReports</Link>
        </li>
        <li>
          <Link to="/helpcenter">HelpCenter</Link>
        </li>
        <li>
          <Link to="/screenshoteditor">ScreenshotEditor</Link>
        </li>
        <li>
          <Link to="/storecredits">StoreCredits</Link>
        </li>
        <li>
          <Link to="/videoads">VideoAds</Link>
        </li>
        <li>
          <Link to="/leechprotection">LeechProtection</Link>
        </li>
        <li>
          <Link to="/splitviewscreen">SplitViewScreen</Link>
        </li>
        <li>
          <Link to="/wishlist">Wishlist</Link>
        </li>
        <li>
          <Link to="/location">Location</Link>
        </li>
        <li>
          <Link to="/syncsettings">SyncSettings</Link>
        </li>
        <li>
          <Link to="/zipcodesearch">ZIPCodeSearch</Link>
        </li>
        <li>
          <Link to="/lostdeviceprotection">LostDeviceProtection</Link>
        </li>
        <li>
          <Link to="/syncoptions">Syncoptions</Link>
        </li>
        <li>
          <Link to="/passcodelock">PasscodeLock</Link>
        </li>
        <li>
          <Link to="/volumecontrol">VolumeControl</Link>
        </li>
        <li>
          <Link to="/passwordstrength">PasswordStrength</Link>
        </li>
        <li>
          <Link to="/worldclock">WorldClock</Link>
        </li>
        <li>
          <Link to="/phoneverification">PhoneVerification</Link>
        </li>
        <li>
          <Link to="/xmlcsvtempalatebuilder">XMLCSVTempalateBuilder</Link>
        </li>
        <li>
          <Link to="/privacysettings">PrivacySettings</Link>
        </li>
        <li>
          <Link to="/privatechat">PrivateChat</Link>
        </li>
        <li>
          <Link to="/editprofile">EditProfile</Link>
        </li>
        <li>
          <Link to="/serchhistory">SerchHistory</Link>
        </li>
        <li>
          <Link to="/securitypolicy">SecurityPolicy</Link>
        </li>
        <li>
          <Link to="/offlinework">Offlinework</Link>
        </li>
        <li>
          <Link to="/sendmessage">SendMessage</Link>
        </li>
        <li>
          <Link to="/signup">SignUp</Link>
        </li>
        <li>
          <Link to="/storelocator">StoreLocator</Link>
        </li>
        <li>
          <Link to="/twitterlogin">Twitterlogin</Link>
        </li>
        <li>
          <Link to="/settingsone">SettingsOne</Link>
        </li>
        <li>
          <Link to="/signin">Signin</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
